Add curative fetcher
CAVaccineInventory/vaccine-feed-ingest pull request #162
Opened 2021-04-24 23:44 UTC by rajbot

Run with `poetry run vaccine-feed-ingest fetch us/curativeinc_com`

Writes one json file per location.

2021-04-28 06:24 UTC, eliblock approved these changes
Thank you for writing this @rajbot!

I've noticed a few other fetchers use `asyncio` to speed up fetches that involve a lot of network calls. Is it worth adding that here?

2021-04-28 06:24 UTC, eliblock commented on vaccine_feed_ingest/runners/us/curativeinc_com/fetch.py
> +    logger.info(f"Fetching {url}")
Let's remove this line - it makes for very noisy logs given the number of sites polled.
```suggestion

```

2021-06-02 02:34 UTC, obra commented
What's this blocking on?

2021-06-02 02:44 UTC, bryanculbertson requested changes
This PR is pretty old at this point. It will need to be rebased to main and have the tests re-run.

It also sounds like it is really slow according to @eliblock 's comment?

2021-06-03 17:44 UTC, MoralCode commented
it looks like the api url here is for testing sites (`https://labtools.curativeinc.com/api/v1/testing_sites`). Is this something that is still needed to add to the map? It is my impression that the map (and this dataset) is just focused on vaccination sites.

2021-06-03 18:24 UTC, obra commented
That data is pretty clearly vaccination clinics. Also, curative's
data includes whether a site is a vaccination clinic or a testing site in
the per-site info.

On Thu, Jun 3, 2021 at 10:44 AM Adrian Edwards ***@***.***>
wrote:

> it looks like the api url here is for testing sites (
> https://labtools.curativeinc.com/api/v1/testing_sites). Is this something
> that is still needed to add to the map? It is my impression that the map
> (and this dataset) is just focused on vaccination sites.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/CAVaccineInventory/vaccine-feed-ingest/pull/162#issuecomment-854059913>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAALC2ANBMXEGXZRYPGEBFTTQ65RDANCNFSM43QUNTUA>
> .
>

2021-08-30 07:55 UTC, eliblock commented
Closing all prs: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down

2021-08-30 07:55 UTC, closed without merging