Refactor stage
CAVaccineInventory/vaccine-feed-ingest pull request #285
Opened 2021-04-29 06:03 UTC by shashank025

# 

| Key Details |
|-|
| Resolves #255 |
State:  |
Site:  |

## Notes

NA

## Data sample

Ran `all-stages` for `ak/arcgis`via:

```
 poetry run vaccine-feed-ingest all-stages ak/arcgis
```

and examined the first line of normalization output via:

```
head -1 out/ak/arcgis/normalized/2021-04-28T22\:44\:45/d92cbd6ff2524d7e92bef109f30cb366_0.parsed.normalized.ndjson
```

```json
{"id": "ak:arcgis:d92cbd6ff2524d7e92bef109f30cb366_0:85b07ac7-c9b6-4d09-83ec-a720998c2fbf", "name": "North Slope Borough Public Health Nursing-Wellness", "address": {"street1": "579 Kongosak St", "street2": null, "city": "Barrow", "state": "AK", "zip": "99723"}, "location": {"latitude": 71.29069998454801, "longitude": -156.7920099649541}, "contact": [{"contact_type": null, "phone": "(907) 852-0270", "website": null, "email": null, "other": null}], "languages": null, "opening_dates": null, "opening_hours": null, "availability": {"drop_in": null, "appointments": true}, "inventory": [{"vaccine": "pfizer_biontech", "supply_level": null}], "access": null, "parent_organization": null, "links": null, "notes": ["NSB PHN Wellness clinic, please call for appointments 907-852-0270"], "active": null, "source": {"source": "ak:arcgis", "id": "85b07ac7-c9b6-4d09-83ec-a720998c2fbf", "fetched_from_uri": "https://services1.arcgis.com/WzFsmainVTuD5KML/ArcGIS/rest/services/COVID19_Vaccine_Site_Survey_API/FeatureServer/0", "fetched_at": "2021-04-29T05:44:55.676901", "published_at": "2020-12-25T13:00:00", "data": {"attributes": {"address": "579 Kongosak St", "city": "Barrow", "cost_other": null, "datesubmited": 1608930000000, "flu_acceptsInsurance": "yes_please_contact_your_insuran", "flu_cost": "no_cost", "flu_vaccinations": "pfizer", "flu_walkins": "no_please_make_an_appointment", "globalid": "85b07ac7-c9b6-4d09-83ec-a720998c2fbf", "needs_review": "approved", "objectid": 9, "phone": "907-852-0270", "publicEmail": null, "publicNotes": "NSB PHN Wellness clinic, please call for appointments 907-852-0270", "publicWebsite": null, "vaccinationSite": "North Slope Borough Public Health Nursing-Wellness", "zipcode": "99723"}, "geometry": {"spatialReference": {"latestWkid": 4326, "wkid": 4326}, "x": -156.7920099649541, "y": 71.29069998454801}}}}
```

## Before Opening a PR
- [x] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [x] I ran auto-formatting: `poetry run tox -e lint-fix`

2021-04-29 07:43 UTC, bryanculbertson commented on vaccine_feed_ingest/stages/ingest.py
> +def resolve_executable(
Can you move this helper into `site.py`?

2021-04-29 07:46 UTC, bryanculbertson approved these changes
Thank you for refactoring this!

2021-04-29 21:39 UTC, bryanculbertson requested changes
Can you move the helper into `site.py` and then I will merge this

2021-04-30 00:00 UTC, shashank025 commented
> Can you move the helper into `site.py` and then I will merge this

done!

2021-04-30 01:52 UTC, eliblock commented
Hi! Sorry - it looks like this got swept up in the change for #278 . Could you pull in the latest `main` once more... then it seems like we'll be good to go?

2021-04-30 02:24 UTC, shashank025 commented
I've mostly worked with Mercurial at `$work`, so I'm not super familiar with PR merges, but it looks like this is now in a weird state; specifically, I intended only 3 files to be changed, but I see 22 files in the *Files Changed* section, and it seems like @bryanculbertson added some commits to this PR. Should I wait for one of you to merge my changes in, or would you like me to try and fix this branch?

2021-04-30 02:25 UTC, shashank025 commented
Ahh never mind, it looks like I need to fix some lint/test issues - let me do that first.

2021-04-30 02:27 UTC, eliblock commented
@shashank025 hold off on fixing lint/test - since you are now modifying a bunch of files in this PR, some are in a weird state.

@bryanculbertson or I can help get this sorted out this evening. Sorry for the git confusion!

2021-04-30 02:32 UTC, shashank025 commented
> @shashank025 hold off on fixing lint/test - since you are now modifying a bunch of files in this PR, some are in a weird state.
> 
> @bryanculbertson or I can help get this sorted out this evening. Sorry for the git confusion!

Oops, I did another merge before  I read your reply. But I'll stop messing with this branch starting now!

2021-04-30 02:35 UTC, bryanculbertson commented
@shashank025 I'll take a look at this in an hour and clean it up. Sorry for all of the confusiion

2021-04-30 04:59 UTC, eliblock commented
This was tricky - I ended up moving the diff over to #299 rather than reducing this one.

Closing this PR in favor of that one.

2021-04-30 04:59 UTC, closed without merging