Parse Pinal county public health for AZ
CAVaccineInventory/vaccine-feed-ingest pull request #320
Opened 2021-05-01 06:04 UTC by cdjj

| Key Details |
|-|
| Resolves #281  |
State: AZ |
Site:  |

## Data sample
```json
{"providerName": "San Tan Valley Pinal County Public Health Clinic", "city": "San Tan Valley "}
{"providerName": "Mammoth Pinal County Public Health Clinic", "city": "Mammoth"}
{"providerName": "Casa Grande Pinal County Public Health Clinic", "city": "Casa Grande"}
{"providerName": "Apache Junction Pinal County Public Health Clinic", "city": "Apache Junction"}
{"providerName": "Coolidge Pinal County Public Health Clinic", "city": "Coolidge"}
{"providerName": "Maricopa Pinal County Public Health Clinic", "city": "Maricopa"}
{"providerName": "Embry Health TestNOW (and Vaccines)", "city": "San Tan Valley", "address": "32375 N Gantzel RD, San Tan Valley, AZ 85143", "website": "https://app.backstagemedical.co/widgets/#/schedule-appointment?pId=9567&widgetType=allopen&typeId=1547&count=300", "phoneNumber": "(480) 376-2170"}
```

## Before Opening a PR
- [X] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [X] I ran auto-formatting: `poetry run tox -e lint-fix`

2021-05-01 20:54 UTC, eliblock requested changes
This parser looks like a great start, but I think we're missing several of the sites [listed on the fetch'd page](https://www.pinalcountyaz.gov/publichealth/CoronaVirus/Pages/vaccinelocations.aspx). Specifically, it looks like there's about 30 parsed rows right now, but I count over 50 sites on the original page.

Could you take another look at why some of the sites might be getting dropped?

2021-05-01 21:48 UTC, cdjj commented on vaccine_feed_ingest/runners/az/pinal_ph_vaccinelocations_gov/parse.py
> +        if address.startswith("Dexcom"):  # Special case, they don't give the address.
There won't be extra --- this is a company warehouse that's being used as an indoor drive-through site b/c of heat outside, and they've only got the one warehouse (https://azgovernor.gov/governor/news/2021/03/indoor-drive-thru-covid-19-vaccination-site-mesa-will-maintain-vital-east).  There will be additional indoor drive-throughs at other sites, but they'll have other names.

2021-05-01 22:00 UTC, cdjj commented
> Could you take another look at why some of the sites might be getting dropped?

It looks like they edit this by hand and have a stray `</tr>` in there, which confuses Beautiful Soup into ignoring anything after it in the table.  Taking a look to see if there's any way to tell it to accept invalid HTML....

```
  <td>
  <a href="https://www.mhealthappointments.com/covidappt" target="_blank">Register Here</a> <br> <br>
  <b>Administering Janssen-limited supply</b>
  </td>
  <td></td>
  </tr> 
   
  </tr>
   
  <tr>
  <td style="background-color:#FFFF00;">Federal</td>
  <td> Safeway/Albertsons </td>
```

2021-05-01 22:06 UTC, cdjj commented
OK, swapping the parser looks like it ignores the spurious `</tr>` and finds 52 sites.

2021-05-01 22:42 UTC, cdjj commented on vaccine_feed_ingest/runners/az/pinal_ph_vaccinelocations_gov/parse.py
> +        if address.startswith("Dexcom"):  # Special case, they don't give the address.
(Also, the text we get is "Dexcom Site", so there's not much more to disambiguate with....)

2021-05-02 01:07 UTC, eliblock commented on vaccine_feed_ingest/runners/az/pinal_ph_vaccinelocations_gov/parse.py
> +        if address.startswith("Dexcom"):  # Special case, they don't give the address.
Thank you for doing the extra research!

2021-05-02 01:08 UTC, eliblock approved these changes
Thank you for taking a second look!

2021-05-02 01:08 UTC, merged