Add fetch step for wv/dhhr. Fixes #368.
CAVaccineInventory/vaccine-feed-ingest pull request #541
Opened 2021-05-04 13:09 UTC by skbdpup

# Fetch dhhr for WV

| Key Details |
|-|
| Resolves #368 |
State: WV |
Site: dhhr |

## Data sample
```html
<p style="margin:0in"><b><u><span style="font-size:11pt"><font color="#000000" face="Calibri">Tuesday, March 2, 2021</font></span></u></b></p>
<font color="#000000" face="Times New Roman" size="3">

</font><p style="margin:0in;text-align:justify"><b><span style="font-size:11pt"><font color="#000000" face="Calibri">Cabell County (All clinic appointments have
been assigned)</font></span></b></p>
<font color="#000000" face="Times New Roman" size="3">

</font><p style="margin:0in;text-align:justify"><b><span style="color:black;font-family:calibri, sans-serif;font-size:11pt">11:00 a.m. - 4:00 p.m.</span></b><span style="font-family:calibri, sans-serif;font-size:11pt"><font color="#000000">,<b> </b></font></span><span style="color:black;font-family:calibri, sans-serif;font-size:11pt">COVID-19 Vaccine Center (old Sears store)</span><span style="font-family:calibri, sans-serif;font-size:11pt"><font color="#000000">, </font></span><span style="color:black;font-family:calibri, sans-serif;font-size:11pt">100
Huntington Mall Road, Barboursville, WV 25504</span><span style="font-family:calibri, sans-serif;font-size:11pt"><font color="#000000">. By appointment only.</font></span></p>
```

## Before Opening a PR
- [x] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [x] I ran auto-formatting: `poetry run tox -e lint-fix`

2021-05-04 13:10 UTC, skbdpup commented on vaccine_feed_ingest/runners/wv/dhhr/fetch.sh
> +    echo "Must pass an output_dir as first argument"
Should we `exit 1` here?
And should we print the error message to stderr?

2021-05-04 15:51 UTC, bryanculbertson requested changes
Thank you for working on this fetch stage! It looks like this site is going to be a little harder than most since they use a different URL for each weekly update of the clinics!

Can you make this fetcher smarter? It needs to grab the latest "Vaccination Clinics" URL from the news page: https://dhhr.wv.gov/News/2021/Pages/default.aspx

Which for this week is: `https://dhhr.wv.gov/News/2021/Pages/COVID-19-Vaccination-Clinics-May-3-8,-2021.aspx`

And then fetch that url.

Thank you!

2021-05-09 04:25 UTC, bryanculbertson commented
@skbdpup I just noticed that you requested a review 3 days ago! Sorry about missing this, reviewing now.

2021-05-09 04:27 UTC, bryanculbertson approved these changes
This looks great. Thank you for figuring out how to grab the latest URL, and for documenting the process.

2021-05-09 04:27 UTC, merged