parse street addres from GISCorps dataset using usaddress library
CAVaccineInventory/vaccine-feed-ingest pull request #677
Opened 2021-05-21 05:30 UTC by MoralCode

| Key Details |
|-|
State: us |
Site: giscorps_vaccine_providers |

## Notes
update parsing to attempt to parse addresses.

There seem to still be many addresses that are ambiguous, but this gets the majority that are fully-qualified

## Before Opening a PR
- [ X] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [ X] I ran auto-formatting: `poetry run tox -e lint-fix`

2021-05-26 04:54 UTC, eliblock requested changes
@MoralCode - as discussed offline, it looks like this update currently prevents the normalizer from running. Could you take another look?

Be sure to run `poetry run vaccine-feed-ingest all-stages us/giscorps_vaccine_providers` and check the output!

Additionally, you may want to rebase on top of `main`. In #600 we added another user of `usaddress`, and they handled dependency import! (The code from that PR might also help debug this normalizer, though I haven't looked closely).

2021-05-27 01:36 UTC, MoralCode commented
@eliblock seems to run fine for me. what problem were you seeing where it was stopping the normalizer from running?

also what do you mean "they handled dependency import"? `usaddress` is imported the same in both PR's

2021-05-27 01:36 UTC, MoralCode commented
also, would it help to hold off and integrate this with #691?

2021-05-28 04:05 UTC, eliblock commented
@MoralCode great suggestion - let's build this on top of #691!

2021-05-28 21:42 UTC, MoralCode commented
@eliblock rebased on top of the latest main branch and updated to utilize the utility parser from the mentioned PR. Should now be good to go

2021-06-02 02:54 UTC, bryanculbertson approved these changes

2021-06-02 02:54 UTC, bryanculbertson commented on vaccine_feed_ingest/runners/us/giscorps_vaccine_providers/normalize.py
> +    us_state_abbrev = {
For a followup PR, you can convert this to use the `us` library.

e.g.
```
import us
us.states.lookup('maryland')
```

2021-06-02 02:54 UTC, bryanculbertson commented
Approving and merging. There is some followup work to use `us` library if you want to simplify your code somewhat

2021-06-02 02:55 UTC, merged