Fixed installation script for mac.
CAVaccineInventory/vaccine-feed-ingest pull request #692
Opened 2021-05-27 19:24 UTC by MaxBrady

* `set -e` was causing maybe_install to fail when a package was not installed. `which $1` was returning an error when the package was not installed.
* Did not make any changes to Linux install function.
* Getting an error installing poppler:
    ==> Installing gdal dependency: poppler
    Error: Cannot install poppler because conflicting formulae are installed.
    pdftohtml: because poppler, pdftohtml, pdf2image, and xpdf install conflicting executables
This error is unrelated to the script as it is reproducible using manual install steps. I have not been able to resolve this error yet.

# 

| Key Details |
|-|
| Resolves # |
State:  |
Site:  |

## Notes

## Data sample

```json
{...}
```

## Before Opening a PR
- [ ] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [ ] I ran auto-formatting: `poetry run tox -e lint-fix`

2021-06-02 02:34 UTC, obra approved these changes
Looks fine to me. I'd *rather* we fixed maybe_install but don't have the cycles to do that myself, so +1 to merge.

2021-06-02 02:58 UTC, bryanculbertson requested changes

2021-06-02 02:58 UTC, bryanculbertson commented on setup.sh
> -set -u
I think we should keep `set -u` and `set -e` at the top, and then disable them just for the part that we handle errors

e.g. in maybe_install
```
set +e
$3
set -e
```

2021-08-30 07:54 UTC, eliblock commented
Closing all prs: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down

2021-08-30 07:54 UTC, closed without merging